export const palette = {
  primaryBg: "bg-slate-700",
  secondaryBg: "bg-stone-800",
  secondaryBorder: "border-stone-800",
  accentBg: "bg-lime-500",
  accentText: "text-lime-500",
  accentInputRing: "focus:ring-lime-500",
  accentSelectRing: "data-[state=open]:border-lime-500",
  accentForCommandPopover: "data-[selected=true]:bg-stone-800",
  accentForSelectDropDown: "focus:bg-stone-800",
  accentForSelectChevron: "[&_svg:not([class*='text-'])]:text-lime-500",
  linkHover: "hover:text-lime-500",
  buttonHover: "hover:border-lime-500",
  lightBg: "bg-white",
  lightStroke: "stroke-accentForCommandPopoverwhite",
  neutralText: "text-gray-800",
  lightText: "text-white",
  lightCaret: "caret-white",
  infoBg: "bg-teal-400",
  successBg: "bg-green-500",
  warningBg: "bg-amber-300",
  dangerBg: "bg-red-500",
  dangerText: "text-red-500",
  popoverBg: "bg-slate-500",
};
