export const palette = {
  primaryBg: "bg-slate-700",
  secondaryBg: "bg-stone-800",
  secondaryBorder: "border-stone-800",
  accentBg: "bg-lime-500",
  accentText: "text-lime-500",
  linkHover: "hover:text-lime-500",
  neutralBg: "bg-white",
  neutralText: "text-gray-800",
  lightText: "text-white",
  infoBg: "bg-teal-400",
  successBg: "bg-green-500",
  warningBg: "bg-amber-300",
  dangerBg: "bg-red-500",
  dangerText: "text-red-500",
};
